-- AlterTable
ALTER TABLE `product` ADD COLUMN `qty` INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE `productcart` ADD COLUMN `qty` INTEGER NOT NULL DEFAULT 1,
    ALTER COLUMN `price` DROP DEFAULT;
